### ISSUE TITLE
4. Combining data CSVs

### ISSUE THREAD

**Issue by micahkwok** [UBC-MDS/grp15_rainfall_analysis#5]
- [x] Combine data CSVs into a single CSV.
- [x] When combining the csv files make sure to add extra column called "model" that identifies the model (tip : you can get this column populated from the file name eg: for file name "SAM0-UNICON_daily_rainfall_NSW.csv", the model name is SAM0-UNICON)
- [x] Compare run times and memory usages of these options on different machines within your team, and summarize your observations in your milestone notebook.

**Comment by jkim222383** [comment]
![image](https://user-images.githubusercontent.com/57465572/113468947-662af680-93fe-11eb-94da-11a79172292e.png)

**Comment by micahkwok** [comment]
![Screen Shot 2021-04-02 at 11 34 03 PM](https://user-images.githubusercontent.com/70661726/113470620-ead04180-940b-11eb-98ab-5b0399be75f2.png)

**Comment by pan1fan2** [comment]
<img width="1410" alt="Screen Shot 2021-04-03 at 1 12 01 PM" src="https://user-images.githubusercontent.com/30707756/113469222-8f8b6700-947e-11eb-98e4-7afd3ef3af09.png">

**Comment by chuangw6** [comment]
<img width="978" alt="Screen Shot 2021-04-03 at 21 26 36" src="https://user-images.githubusercontent.com/30398455/113498610-51fcfd00-94c3-11eb-9f75-28287d07a576.png">
